version: 2
jobs:
  job_template: &job_template
    environment:
      GEM_HOME: vendor/bundle
      BUNDLER_INSTALL_ARGS: -v 1.17.3
    docker:
      - image: ruby:$CIRCLE_JOB
    working_directory: /tmp/project
    steps:
      - checkout
      - run:
          name: Bundle install
          command: >
            gem install bundler -i vendor/bundle $BUNDLER_INSTALL_ARGS
            && bundle install --path vendor/bundle
      - run:
          name: Run Tests
          command: bundle exec rake spec

  1.9.3:
    <<: *job_template
  2.0.0:
    <<: *job_template
  2.1.1:
    <<: *job_template
  2.2.0:
    <<: *job_template
  2.3.0:
    <<: *job_template
  2.4.0:
    <<: *job_template
  2.5.0:
    <<: *job_template
  2.6.0:
    <<: *job_template

workflows:
  version: 2
  build:
    jobs:
      - 1.9.3
      - 2.0.0
      - 2.1.1
      - 2.2.0
      - 2.3.0
      - 2.4.0
      - 2.5.0
      - 2.6.0
